# Configuration file for WebStats
# See https://github.com/Dantevg/WebStats#plugin-config-file for more info

# Port to use for the service. Make sure that this port corresponds
# to the one set in the web page js script
port: 8080

# Only these columns will appear, in the order specified.
# When commented out, all columns will be displayed, in alphabetical order (default)
# The 'Player' column will always be displayed, as the first column.
#columns: []

# Scoreboard objectives to use. When '*' is present, uses all objectives.
# (make sure to enclose the '*' in quotes)
objectives:
  - '*'

# Configuration for the MySQL database connectivity (uncomment to use)
#database:
#  hostname: localhost
#  username: DATABASE USERNAME
#  password: DATABASE PASSWORD
#  config:
#    - database: DATABASE NAME
#      table: TABLE NAME
#      convert: # Some examples, refer to documentation for explanations
#        - [rename, from-column, to-column]
#        - [json, column]
#        - [key-value, key-column, value-column]
#        - [uuid, column]

# Configuration for the PlaceholderAPI connectivity (uncomment to use)
#placeholders:
#  '%placeholder_name%': displayed name
